export const AssessmentQuestions = {
    SDPC: {

        "Educational Test": {
            "Set 1": [
            //BS Information Technology
                {Question: `I've always been interested in technology`, 
                    SubCategory: "BS Information Technology", MainCategory: "Set 1"},
                {Question: `I find working on a computer spreadsheet or database rewarding`, 
                    SubCategory: "BS Information Technology", MainCategory: "Set 1"},
                {Question: `I am good with software and hardware.`, 
                    SubCategory: "BS Information Technology", MainCategory: "Set 1"},
                {Question: `I enjoy making things for future development.`, 
                    SubCategory: "BS Information Technology", MainCategory: "Set 1"},
                {Question: `I prefer to spend my free time studying alone.`, 
                    SubCategory: "BS Information Technology", MainCategory: "Set 1"},
            //BS Criminology
                {Question: "I would rather be a public relations professional.", 
                    SubCategory: "BS Criminology", MainCategory: "Set 1"},
                {Question: "I follow the instructions and commands of my leader.", 
                    SubCategory: "BS Criminology", MainCategory: "Set 1"},
                {Question: "I am keen to find out the cause of a problem.", 
                    SubCategory: "BS Criminology", MainCategory: "Set 1"},
                {Question: "I care about the safety of other people.", 
                    SubCategory: "BS Criminology", MainCategory: "Set 1"},
                {Question: "I am most comfortable following a schedule.", 
                    SubCategory: "BS Criminology", MainCategory: "Set 1"},
            //BS Psychology
                {Question: `I care about the well being of other people`, 
                    SubCategory: "BS Psychology", MainCategory: "Set 1"},
                {Question: `I see things as they could be.`, 
                    SubCategory: "BS Psychology", MainCategory: "Set 1"},
                {Question: `I am sensitive to other people's feelings.`, 
                    SubCategory: "BS Psychology", MainCategory: "Set 1"},
                {Question: `I want them to know me that I'm passionate and sensitive to others.`, 
                    SubCategory: "BS Psychology", MainCategory: "Set 1"},
                {Question: `I often give advice to others.`, 
                    SubCategory: "BS Psychology", MainCategory: "Set 1"},
            //BS Nursing
                {Question: `I want to develop tolerance, respect, self awareness and interpersonal skills for my professional career.`, 
                    SubCategory: "BS Nursing", MainCategory: "Set 1"},
                {Question: `Effective listening is one of the most important skills that I should possess`, 
                    SubCategory: "BS Nursing", MainCategory: "Set 1"},
                {Question: `I'm goal-driven and good at staying the course.`, 
                    SubCategory: "BS Nursing", MainCategory: "Set 1"},
                {Question: `I love helping people, no matter what.`, 
                    SubCategory: "BS Nursing", MainCategory: "Set 1"},
                {Question: `I like making sure everyone has what they need.`, 
                    SubCategory: "BS Nursing", MainCategory: "Set 1"},
            //BS Computer Engineering
                {Question: `I have an accurate coding skills.`, 
                    SubCategory: "BS Computer Engineering", MainCategory: "Set 1"},
                {Question: `The decisions of others is valuable to me.`, 
                    SubCategory: "BS Computer Engineering", MainCategory: "Set 1"},
                {Question: `I also make sure that my finished tasks function effectively in different error situations.`, 
                    SubCategory: "BS Computer Engineering", MainCategory: "Set 1"},
                {Question: `I'm used to collaborating with others on different projects.`, 
                    SubCategory: "BS Computer Engineering", MainCategory: "Set 1"},
                {Question: `I avoid repeating mistakes.`, 
                    SubCategory: "BS Computer Engineering", MainCategory: "Set 1"},
            //BS Electronics Engineering 
                {Question: `I do what helps facilitate the idea that helps improve our daily practices.`, 
                    SubCategory: "BS Electronics Engineering", MainCategory: "Set 1"},
                {Question: `I have been successful in creating things that used effectively.`, 
                    SubCategory: "BS Electronics Engineering", MainCategory: "Set 1"},
                {Question: `I first determine the tasks then I will proceed on finishing it.`, 
                    SubCategory: "BS Electronics Engineering", MainCategory: "Set 1"},
                {Question: `I do love fixing anything powered by electricity.`, 
                    SubCategory: "BS Electronics Engineering", MainCategory: "Set 1"},
                {Question: `I believe that my skills and knowledge is valuable for the society.`, 
                    SubCategory: "BS Electronics Engineering", MainCategory: "Set 1"},
            //BS Industrial Engineering 
                {Question: `I'm an artistic person who likes to be involved with forms, patterns, and design in life.`, 
                    SubCategory: "BS Industrial Engineering", MainCategory: "Set 1"},
                {Question: `I'm very good at understanding other people's mood and feelings.`, 
                    SubCategory: "BS Industrial Engineering", MainCategory: "Set 1"},
                {Question: `I like doing outdoor, mechanical, and physical activities.`, 
                    SubCategory: "BS Industrial Engineering", MainCategory: "Set 1"},
                {Question: `I'm an extrovert, my energy and ability to take risks is the reason many projects get started and stay successful`, 
                    SubCategory: "BS Industrial Engineering", MainCategory: "Set 1"},
                {Question: `I tend to analyze situations before making decisions.`, 
                    SubCategory: "BS Industrial Engineering", MainCategory: "Set 1"},
            //BS Accountancy 
                {Question: `I enjoyed group projects and also I'd like to do voluntary work`, 
                    SubCategory: "BS Accountancy", MainCategory: "Set 1"},
                {Question: `When there's a problem, I keep looking for solution until I find the answer.`, 
                    SubCategory: "BS Accountancy", MainCategory: "Set 1"},
                {Question: `I like learning about new people, places, and things.`, 
                    SubCategory: "BS Accountancy", MainCategory: "Set 1"},
                {Question: `I can explain complicated concepts in simple ways.`, 
                    SubCategory: "BS Accountancy", MainCategory: "Set 1"},
                {Question: `I'm good at planning strategies to help my team accomplish their goals.`, 
                    SubCategory: "BS Accountancy", MainCategory: "Set 1"},
            //BS Tourism 
                {Question: `I am delighted to see new places that I haven't gone to.`, 
                    SubCategory: "BS Tourism", MainCategory: "Set 1"},
                {Question: `Traveling around is one of my favorite hobbies.`, 
                    SubCategory: "BS Tourism", MainCategory: "Set 1"},
                {Question: `I am passionate about sharing trivial information about historical/famous places that others might not know.`, 
                    SubCategory: "BS Tourism", MainCategory: "Set 1"},
                {Question: `I can learn a lot from visiting other places, its either beliefs, culture, or history.`, 
                    SubCategory: "BS Tourism", MainCategory: "Set 1"},
                {Question: `I can help other people not only to share knowledge about someplace, but also to promote the beauty of our country.`, 
                    SubCategory: "BS Tourism", MainCategory: "Set 1"},
            //BS Hospitality 
                {Question: `I have good listening and communication skills to help people in needs.`, 
                    SubCategory: "BS Hospitality", MainCategory: "Set 1"},
                {Question: `I'm good problem-solver.`, 
                    SubCategory: "BS Hospitality", MainCategory: "Set 1"},
                {Question: `I like developing new types of focused tours or attractive themes.`, 
                    SubCategory: "BS Hospitality", MainCategory: "Set 1"},
                {Question: `I'm good at keeping important information assigned to me.`, 
                    SubCategory: "BS Hospitality", MainCategory: "Set 1"},
                {Question: `I can be an effective leader or a creative thinker.`, 
                    SubCategory: "BS Hospitality", MainCategory: "Set 1"},
            //AB Communication 
                {Question: `I always look for new opportunities.`, 
                    SubCategory: "AB Communication", MainCategory: "Set 1"},
                {Question: `I want to learn to communicate on every languages.`, 
                    SubCategory: "AB Communication", MainCategory: "Set 1"},
                {Question: `I'm confident to communicate to people.`, 
                    SubCategory: "AB Communication", MainCategory: "Set 1"},
                {Question: `I want to learn and improve when it comes writing and communication skills.`, 
                    SubCategory: "AB Communication", MainCategory: "Set 1"},
                {Question: `I really like to try public speaking but I'm not confident to do that.`, 
                    SubCategory: "AB Communication", MainCategory: "Set 1"},
            //BSBA Management Accounting   
                {Question: `I have conducted myself in a respectable manner with appropriate knowledge, values, and attitudes. `, 
                    SubCategory: "BSBA Management Accounting", MainCategory: "Set 1"},
                {Question: `I'm good at making strategic and operating decisions. `, 
                    SubCategory: "BSBA Management Accounting", MainCategory: "Set 1"},
                {Question: `I'm good at mathematical concepts and operations.`, 
                    SubCategory: "BSBA Management Accounting", MainCategory: "Set 1"},
                {Question: `I have the ability to identify, assess, create alternative solutions and solve the actual problem while continuously evaluating for outcomes.`, 
                    SubCategory: "BSBA Management Accounting", MainCategory: "Set 1"},
                {Question: `I have a small knowledge of using computer and can understand known application programs.`, 
                    SubCategory: "BSBA Management Accounting", MainCategory: "Set 1"},
            //BSBA Financial Management   
                {Question: `I'm conventional person who is careful, quiet, and pay attention to detail.`, 
                    SubCategory: "BSBA Financial Management", MainCategory: "Set 1"},
                {Question: `I'm the person who enjoys solving problems.`, 
                    SubCategory: "BSBA Financial Management", MainCategory: "Set 1"},
                {Question: `I'm good at decision-making and analytical abilities.`, 
                    SubCategory: "BSBA Financial Management", MainCategory: "Set 1"},
                {Question: `I'm always prepared to connect with people through a variety of channels, including emails, phone calls, instant messages, and face-to-face meetings.`, 
                    SubCategory: "BSBA Financial Management", MainCategory: "Set 1"},
                {Question: `I'm the person who can study the market strategies and managing funds.`, 
                    SubCategory: "BSBA Financial Management", MainCategory: "Set 1"},
            //BSBA Marketing Management   
                {Question: `I have listening skills to understand clients or executives wants and needs.`, 
                    SubCategory: "BSBA Marketing Management", MainCategory: "Set 1"},
                {Question: `I want to develop promotional strategies and interpersonal skills to work with different personality types.`, 
                    SubCategory: "BSBA Marketing Management", MainCategory: "Set 1"},
                {Question: `With my communication skills, I can cooperate effectively when it comes to marketing campaign.`, 
                    SubCategory: "BSBA Marketing Management", MainCategory: "Set 1"},
                {Question: `I understand how bad ideas affects consumer behavior.`, 
                    SubCategory: "BSBA Marketing Management", MainCategory: "Set 1"},
                {Question: `I'm good at motivating myself, my teams, and others.`, 
                    SubCategory: "BSBA Marketing Management", MainCategory: "Set 1"},
            ]
            
        },
            
        "Mental Health Test":{

            "Mood Disorders":[
                {Question: `I often experience feelings of sadness that persist for an extended period.`, 
                    SubCategory: "Depression", MainCategory: "Mood Disorders"},
                {Question: `I have lost interest in activities that used to bring me joy.`, 
                    SubCategory: "Depression", MainCategory: "Mood Disorders"},
                {Question: `Hopelessness is a recurring emotion in my daily life.`, 
                    SubCategory: "Depression", MainCategory: "Mood Disorders"},
                {Question: `I find it challenging to concentrate or make decisions due to my mood.`, 
                    SubCategory: "Depression", MainCategory: "Mood Disorders"},
                {Question: `I struggle with feelings of low energy and motivation.`, 
                    SubCategory: "Depression", MainCategory: "Mood Disorders"},
                {Question: `I experience extreme mood swings, ranging from intense highs to deep lows.`, 
                    SubCategory: "Bipolar Disorder", MainCategory: "Mood Disorders"},
                {Question: `There are times when I feel overly energetic and impulsive.`, 
                    SubCategory: "Bipolar Disorder", MainCategory: "Mood Disorders"},
                {Question: `I find it difficult to maintain a consistent mood for an extended period.`, 
                    SubCategory: "Bipolar Disorder", MainCategory: "Mood Disorders"},
                {Question: `My mood changes significantly, affecting my daily activities and relationships.`, 
                    SubCategory: "Bipolar Disorder", MainCategory: "Mood Disorders"},
                {Question: `I have periods of intense creativity and productivity followed by periods of lethargy.`, 
                    SubCategory: "Bipolar Disorder", MainCategory: "Mood Disorders"},
                {Question: `I experience mood swings that are less severe than bipolar disorder but last for an extended time.`, 
                    SubCategory: "Cyclothymia", MainCategory: "Mood Disorders"},
                {Question: `My mood fluctuations impact my relationships and daily functioning.`, 
                    SubCategory: "Cyclothymia", MainCategory: "Mood Disorders"},
                {Question: `I find it challenging to predict or control my mood swings.`, 
                    SubCategory: "Cyclothymia", MainCategory: "Mood Disorders"},
                {Question: `My mood shifts are noticeable to those around me.`, 
                    SubCategory: "Cyclothymia", MainCategory: "Mood Disorders"},
                {Question: `I have periods of feeling both elevated and low, but not to the extremes seen in bipolar disorder.`, 
                    SubCategory: "Cyclothymia", MainCategory: "Mood Disorders"},
            ],
            
            "Anxiety Disorders": [
                {Question: `Do you find yourself constantly worrying about everyday situations?`, 
                    SubCategory: "Generalized Anxiety Disorder (GAD)", MainCategory: "Anxiety Disorders"},
                {Question: `Does anxiety interfere with your ability to concentrate on daily tasks?`, 
                    SubCategory: "Generalized Anxiety Disorder (GAD)", MainCategory: "Anxiety Disorders"},
                {Question: `Are you often preoccupied with thoughts of potential negative outcomes?`, 
                    SubCategory: "Generalized Anxiety Disorder (GAD)", MainCategory: "Anxiety Disorders"},
                {Question: `Do you experience physGeneralized Anxiety Disorder (GAD)ical symptoms such as muscle tension due to persistent worry?`, 
                    SubCategory: "", MainCategory: "Anxiety Disorders"},
                {Question: `Is it challenging for you to control your anxiety, even when there is no apparent reason?`, 
                    SubCategory: "Generalized Anxiety Disorder (GAD)", MainCategory: "Anxiety Disorders"},
                {Question: `Have you ever experienced sudden episodes of intense fear or panic?`, 
                    SubCategory: "Panic Disorder", MainCategory: "Anxiety Disorders"},
                {Question: `Do these episodes involve physical symptoms like a racing heart or shortness of breath?`, 
                    SubCategory: "Panic Disorder", MainCategory: "Anxiety Disorders"},
                {Question: `Have you ever felt a sense of impending doom during these panic episodes?`, 
                    SubCategory: "Panic Disorder", MainCategory: "Anxiety Disorders"},
                {Question: `Do you avoid situations that you fear might trigger a panic attack?`, 
                    SubCategory: "Panic Disorder", MainCategory: "Anxiety Disorders"},
                {Question: `Are you concerned about having another panic attack in the future?`, 
                    SubCategory: "Panic Disorder", MainCategory: "Anxiety Disorders"},
                {Question: `Do you experience a significant fear of social situations?`, 
                    SubCategory: "Social Anxiety Disorder", MainCategory: "Anxiety Disorders"},
                {Question: `Are you afraid of being judged or criticized by others in social settings?`, 
                    SubCategory: "Social Anxiety Disorder", MainCategory: "Anxiety Disorders"},
                {Question: `Does the fear of embarrassment or humiliation affect your social interactions?`, 
                    SubCategory: "Social Anxiety Disorder", MainCategory: "Anxiety Disorders"},
                {Question: `Do you often avoid social situations to prevent anxiety?`, 
                    SubCategory: "Social Anxiety Disorder", MainCategory: "Anxiety Disorders"},
                {Question: `Have you noticed physical symptoms, such as blushing or sweating, during social events?`, 
                    SubCategory: "Social Anxiety Disorder", MainCategory: "Anxiety Disorders"},
                {Question: `Do you have an intense and irrational fear of specific objects or situations?`, 
                    SubCategory: "Phobias", MainCategory: "Anxiety Disorders"},
                {Question: `Does the fear trigger an immediate and strong anxiety response?`, 
                    SubCategory: "Phobias", MainCategory: "Anxiety Disorders"},
                {Question: `Do you go to great lengths to avoid the feared object or situation?`, 
                    SubCategory: "Phobias", MainCategory: "Anxiety Disorders"},
                {Question: `Is the fear disproportionate to the actual threat posed by the object or situation?`, 
                    SubCategory: "Phobias", MainCategory: "Anxiety Disorders"},
                {Question: `Have you had this fear for an extended period, and does it impact your daily life?`, 
                    SubCategory: "Phobias", MainCategory: "Anxiety Disorders"},
                {Question: `Do you experience unwanted and intrusive thoughts that cause anxiety?`, 
                    SubCategory: "Obsessive-Compulsive Disorder (OCD)", MainCategory: "Anxiety Disorders"},
                {Question: `Do you engage in repetitive behaviors or rituals to reduce anxiety?`, 
                    SubCategory: "Obsessive-Compulsive Disorder (OCD)", MainCategory: "Anxiety Disorders"},
                {Question: `Are these behaviors time-consuming and difficult to control?`, 
                    SubCategory: "Obsessive-Compulsive Disorder (OCD)", MainCategory: "Anxiety Disorders"},
                {Question: `Do you recognize that your obsessions and compulsions are excessive, yet find it challenging to stop?`, 
                    SubCategory: "Obsessive-Compulsive Disorder (OCD)", MainCategory: "Anxiety Disorders"},
                {Question: `Have these thoughts and behaviors significantly impacted your daily life?`, 
                    SubCategory: "Obsessive-Compulsive Disorder (OCD)", MainCategory: "Anxiety Disorders"},
            ],

            "Trauma-Related Disorders":[
                {Question: `Do you experience flashbacks or vivid memories of a traumatic event?`, 
                    SubCategory: "Post-Traumatic Stress Disorder (PTSD)", MainCategory: "Trauma-Related Disorders"},
                {Question: `Are nightmares related to the traumatic event a frequent occurrence for you?`, 
                    SubCategory: "Post-Traumatic Stress Disorder (PTSD)", MainCategory: "Trauma-Related Disorders"},
                {Question: `Do you actively avoid situations, places, or people that remind you of the trauma?`, 
                    SubCategory: "Post-Traumatic Stress Disorder (PTSD)", MainCategory: "Trauma-Related Disorders"},
                {Question: `Have you noticed an increased state of arousal, such as difficulty sleeping or being easily startled?`, 
                    SubCategory: "Post-Traumatic Stress Disorder (PTSD)", MainCategory: "Trauma-Related Disorders"},
                {Question: `Have these symptoms persisted for an extended period, impacting your daily life?`, 
                    SubCategory: "Post-Traumatic Stress Disorder (PTSD)", MainCategory: "Trauma-Related Disorders"},
                {Question: `Have you experienced symptoms similar to PTSD within a month of a traumatic event?`, 
                    SubCategory: "Acute Stress Disorder (ASD)", MainCategory: "Trauma-Related Disorders"},
                {Question: `Do you have intrusive memories or thoughts about the traumatic event?`, 
                    SubCategory: "Acute Stress Disorder (ASD)", MainCategory: "Trauma-Related Disorders"},
                {Question: `Have you had nightmares related to the trauma shortly after it occurred?`, 
                    SubCategory: "Acute Stress Disorder (ASD)", MainCategory: "Trauma-Related Disorders"},
                {Question: `Do you actively avoid reminders of the traumatic event?`, 
                    SubCategory: "Acute Stress Disorder (ASD)", MainCategory: "Trauma-Related Disorders"},
                {Question: `Have you noticed changes in mood or arousal shortly after the traumatic event?`, 
                    SubCategory: "Acute Stress Disorder (ASD)", MainCategory: "Trauma-Related Disorders"},
            ],

            "Personality Disorders":[
                {Question: `Do you find your emotions to be extremely unstable, with intense and rapid shifts?`, 
                    SubCategory: "Borderline Personality Disorder (BPD)", MainCategory: "Personality Disorders"},
                {Question: `Are your relationships characterized by extremes, such as intense closeness and then sudden distance?`, 
                    SubCategory: "Borderline Personality Disorder (BPD)", MainCategory: "Personality Disorders"},
                {Question: `Do you struggle with maintaining a stable and consistent self-image?`, 
                    SubCategory: "Borderline Personality Disorder (BPD)", MainCategory: "Personality Disorders"},
                {Question: `Have you engaged in impulsive behaviors that could be harmful to yourself?`, 
                    SubCategory: "Borderline Personality Disorder (BPD)", MainCategory: "Personality Disorders"},
                {Question: `Do you experience chronic feelings of emptiness or a fear of abandonment?`, 
                    SubCategory: "Borderline Personality Disorder (BPD)", MainCategory: "Personality Disorders"},
                {Question: `Do you have an exaggerated sense of self-importance or superiority?`, 
                    SubCategory: "Narcissistic Personality Disorder", MainCategory: "Personality Disorders"},
                {Question: `Are you preoccupied with fantasies of unlimited success, power, or beauty?`, 
                    SubCategory: "Narcissistic Personality Disorder", MainCategory: "Personality Disorders"},
                {Question: `Do you lack empathy and find it challenging to recognize the needs of others?`, 
                    SubCategory: "Narcissistic Personality Disorder", MainCategory: "Personality Disorders"},
                {Question: `Do you believe that you are entitled to special treatment and admiration?`, 
                    SubCategory: "Narcissistic Personality Disorder", MainCategory: "Personality Disorders"},
                {Question: `Have others pointed out that you often exploit or take advantage of others to achieve your own goals?`, 
                    SubCategory: "Narcissistic Personality Disorder", MainCategory: "Personality Disorders"},
                {Question: `Have you consistently shown a disregard for the rights and feelings of others?`, 
                    SubCategory: "Antisocial Personality Disorder", MainCategory: "Personality Disorders"},
                {Question: `Do you engage in behaviors that involve deceit or manipulation for personal gain?`, 
                    SubCategory: "Antisocial Personality Disorder", MainCategory: "Personality Disorders"},
                {Question: `Have you demonstrated a pattern of impulsivity and irresponsibility?`, 
                    SubCategory: "Antisocial Personality Disorder", MainCategory: "Personality Disorders"},
                {Question: `Did you engage in aggressive conduct during childhood, such as bullying or cruelty to animals?`, 
                    SubCategory: "Antisocial Personality Disorder", MainCategory: "Personality Disorders"},
                {Question: `Have you had a history of legal issues and conflicts with authority figures?`, 
                    SubCategory: "Antisocial Personality Disorder", MainCategory: "Personality Disorders"},
            ],

            "Other Mental Health Problems":[
                {Question: `Do you experience distortions in your thoughts or difficulty distinguishing reality from fantasy?`, 
                    SubCategory: "Schizophrenia", MainCategory: "Other Mental Health Problems"},
                {Question: `Have you noticed disruptions in your perceptions, such as hearing voices or having visual hallucinations?`, 
                    SubCategory: "Schizophrenia", MainCategory: "Other Mental Health Problems"},
                {Question: `Do you find it challenging to express emotions appropriately or to connect with others socially?`, 
                    SubCategory: "Schizophrenia", MainCategory: "Other Mental Health Problems"},
                {Question: `Have you experienced disruptions in your ability to think logically and coherently?`, 
                    SubCategory: "Schizophrenia", MainCategory: "Other Mental Health Problems"},
                {Question: `Have these symptoms persisted, impacting your daily life and functioning?`, 
                    SubCategory: "Schizophrenia", MainCategory: "Other Mental Health Problems"},
                {Question: `Do you experience hallucinations, such as hearing voices or seeing things that others do not?`, 
                    SubCategory: "Psychotic disorders", MainCategory: "Other Mental Health Problems"},
                {Question: `Have you had delusions, which are strongly held false beliefs that contradict reality?`, 
                    SubCategory: "Psychotic disorders", MainCategory: "Other Mental Health Problems"},
                {Question: `Do these symptoms significantly impact your ability to maintain relationships and perform daily tasks?`, 
                    SubCategory: "Psychotic disorders", MainCategory: "Other Mental Health Problems"},
                {Question: `Have others expressed concern about your perceptions of reality?`, 
                    SubCategory: "Psychotic disorders", MainCategory: "Other Mental Health Problems"},
                {Question: `Have you ever felt as though you were losing touch with reality?`, 
                    SubCategory: "Psychotic disorders", MainCategory: "Other Mental Health Problems"},
                {Question: `Do you find yourself dependent on substances, such as drugs or alcohol, to cope with life?`, 
                    SubCategory: "Addiction", MainCategory: "Other Mental Health Problems"},
                {Question: `Have yAddictionou noticed a pattern of increasing tolerance, needing more of a substance to achieve the same effect?`, 
                    SubCategory: "", MainCategory: "Other Mental Health Problems"},
                {Question: `Do you engage in behaviors like gambling excessively, despite negative consequences?`, 
                    SubCategory: "Addiction", MainCategory: "Other Mental Health Problems"},
                {Question: `Have you attempted to cut down or control your substance use or addictive behaviors without success?`, 
                    SubCategory: "Addiction", MainCategory: "Other Mental Health Problems"},
                {Question: `Do you experience withdrawal symptoms when not engaging in the addictive behavior or substance use?`, 
                    SubCategory: "Addiction", MainCategory: "Other Mental Health Problems"},
                {Question: `Have you noticed a decline in your cognitive abilities, such as memory, reasoning, and problem-solving?`, 
                    SubCategory: "Dementia", MainCategory: "Other Mental Health Problems"},
                {Question: `Do you have difficulty remembering recent events or familiar faces?`, 
                    SubCategory: "Dementia", MainCategory: "Other Mental Health Problems"},
                {Question: `Have others observed changes in your personality or mood that are not typical for you?`, 
                    SubCategory: "Dementia", MainCategory: "Other Mental Health Problems"},
                {Question: `Is there a history of dementia or cognitive decline in your family?`, 
                    SubCategory: "Dementia", MainCategory: "Other Mental Health Problems"},
                {Question: `Have these cognitive changes impacted your ability to perform daily tasks independently?`, 
                    SubCategory: "Dementia", MainCategory: "Other Mental Health Problems"},
            ],
        },
        "Personality Test":{
            "Set 1": [
                // Analyst
                    // Architect (INTJ-A / INTJ-T)
                {Question: `I often find myself planning ahead and having a clear strategy for my goals.`, 
                    SubCategory: "Architect (INTJ-A / INTJ-T)", MainCategory: "Analyst"},
                {Question: `I enjoy thinking about innovative solutions to complex problems.`, 
                    SubCategory: "Architect (INTJ-A / INTJ-T)", MainCategory: "Analyst"},
                {Question: `I believe it's important to have a plan for every aspect of life.`, 
                    SubCategory: "Architect (INTJ-A / INTJ-T)", MainCategory: "Analyst"},
                    // Logician (INTP-A / INTP-T)
                {Question: `I have an insatiable curiosity and thirst for knowledge.`, 
                    SubCategory: "Logician (INTP-A / INTP-T)", MainCategory: "Analyst"},
                {Question: `I enjoy exploring abstract ideas and theoretical concepts.`, 
                    SubCategory: "Logician (INTP-A / INTP-T)", MainCategory: "Analyst"},
                {Question: `I find it challenging to stick to a rigid plan; flexibility is key to my approach.`, 
                    SubCategory: "Logician (INTP-A / INTP-T)", MainCategory: "Analyst"},
                    // Commander (ENTJ-A / ENTJ-T)
                {Question: `I see myself as a bold and strong-willed leader.`, 
                    SubCategory: "Commander (ENTJ-A / ENTJ-T)", MainCategory: "Analyst"},
                {Question: `I enjoy taking charge and finding solutions to challenges.`, 
                    SubCategory: "Commander (ENTJ-A / ENTJ-T)", MainCategory: "Analyst"},
                {Question: `I believe in creating opportunities and making things happen.`, 
                    SubCategory: "Commander (ENTJ-A / ENTJ-T)", MainCategory: "Analyst"},
                    // Debater (ENTP-A / ENTP-T)
                {Question: `I see myself as a bold and strong-willed leader.`, 
                    SubCategory: "Debater (ENTP-A / ENTP-T)", MainCategory: "Analyst"},
                {Question: `I enjoy taking charge and finding solutions to challenges.`, 
                    SubCategory: "Debater (ENTP-A / ENTP-T)", MainCategory: "Analyst"},
                {Question: `I believe in creating opportunities and making things happen.`, 
                    SubCategory: "Debater (ENTP-A / ENTP-T)", MainCategory: "Analyst"},
                    
                // Diplomat
                    // Advocate (INFJ-A / INFJ-T)
                {Question: `I am often inspired by idealistic and mystical concepts.`, 
                    SubCategory: "Advocate (INFJ-A / INFJ-T)", MainCategory: "Diplomat"},
                {Question: `I enjoy helping others and working toward a greater cause.`, 
                    SubCategory: "Advocate (INFJ-A / INFJ-T)", MainCategory: "Diplomat"},
                {Question: `I see myself as a tireless idealist with a quiet strength.`, 
                    SubCategory: "Advocate (INFJ-A / INFJ-T)", MainCategory: "Diplomat"},
                    // Mediator (INFP-A / INFP-T)
                {Question: `I am naturally poetic and value kindness in my interactions.`, 
                    SubCategory: "Mediator (INFP-A / INFP-T)", MainCategory: "Diplomat"},
                {Question: `I find fulfillment in altruistic actions and helping those in need.`, 
                    SubCategory: "Mediator (INFP-A / INFP-T)", MainCategory: "Diplomat"},
                {Question: `I am driven by a desire to make the world a better place.`, 
                    SubCategory: "Mediator (INFP-A / INFP-T)", MainCategory: "Diplomat"},
                    // Protagonist (ENFJ-A / ENFJ-T)
                {Question: `I consider myself a charismatic and inspiring leader.`, 
                    SubCategory: "Protagonist (ENFJ-A / ENFJ-T)", MainCategory: "Diplomat"},
                {Question: `I am drawn to opportunities to motivate and mesmerize others.`, 
                    SubCategory: "Protagonist (ENFJ-A / ENFJ-T)", MainCategory: "Diplomat"},
                {Question: `I believe in the power of leadership to create positive change.`, 
                    SubCategory: "Protagonist (ENFJ-A / ENFJ-T)", MainCategory: "Diplomat"},
                    // Campaigner (ENFP-A / ENFP-T)
                {Question: `I see myself as an enthusiastic and sociable free spirit.`, 
                    SubCategory: "Campaigner (ENFP-A / ENFP-T)", MainCategory: "Diplomat"},
                {Question: `I enjoy creative endeavors and find reasons to smile in any situation.`, 
                    SubCategory: "Campaigner (ENFP-A / ENFP-T)", MainCategory: "Diplomat"},
                {Question: `I thrive on connecting with others and exploring new possibilities.`, 
                    SubCategory: "Campaigner (ENFP-A / ENFP-T)", MainCategory: "Diplomat"},

                // Sentinel
                    // Logistician (ISTJ-A / ISTJ-T)
                {Question: `I value practicality and facts in decision-making.`, 
                    SubCategory: "Logistician (ISTJ-A / ISTJ-T)", MainCategory: "Sentinel"},
                {Question: `I take pride in my reliability and trustworthiness.`, 
                    SubCategory: "Logistician (ISTJ-A / ISTJ-T)", MainCategory: "Sentinel"},
                {Question: `I believe in sticking to proven methods and systems.`, 
                    SubCategory: "Logistician (ISTJ-A / ISTJ-T)", MainCategory: "Sentinel"},
                    // Defender (ISFJ-A / ISFJ-T)
                {Question: `I am dedicated and always ready to protect my loved ones.`, 
                    SubCategory: "Defender (ISFJ-A / ISFJ-T)", MainCategory: "Sentinel"},
                {Question: `I find fulfillment in nurturing and caring for others.`, 
                    SubCategory: "Defender (ISFJ-A / ISFJ-T)", MainCategory: "Sentinel"},
                {Question: `Loyalty is a crucial aspect of my relationships.`, 
                    SubCategory: "Defender (ISFJ-A / ISFJ-T)", MainCategory: "Sentinel"},
                    // Executive (ESTJ-A / ESTJ-T)
                {Question: `I excel in managing tasks and people effectively.`, 
                    SubCategory: "Executive (ESTJ-A / ESTJ-T)", MainCategory: "Sentinel"},
                {Question: `I believe in maintaining order and structure in all aspects of life.`, 
                    SubCategory: "Executive (ESTJ-A / ESTJ-T)", MainCategory: "Sentinel"},
                {Question: `I see myself as an excellent administrator.`, 
                    SubCategory: "Executive (ESTJ-A / ESTJ-T)", MainCategory: "Sentinel"},
                    // Consul (ESFJ-A / ESFJ-T)
                {Question: `I am a caring and social individual who enjoys helping others.`, 
                    SubCategory: "Consul (ESFJ-A / ESFJ-T)", MainCategory: "Sentinel"},
                {Question: `I find joy in being popular and actively participating in social activities.`, 
                    SubCategory: "Consul (ESFJ-A / ESFJ-T)", MainCategory: "Sentinel"},
                {Question: `I believe in the importance of community and collaboration.`, 
                    SubCategory: "Consul (ESFJ-A / ESFJ-T)", MainCategory: "Sentinel"},
                    
                // Explorer
                    // Virtuoso (ISTP-A / ISTP-T)
                {Question: `I enjoy experimenting with practical solutions and tools.`, 
                    SubCategory: "Virtuoso (ISTP-A / ISTP-T)", MainCategory: "Explorer"},
                {Question: `I am comfortable taking bold and calculated risks.`, 
                    SubCategory: "Virtuoso (ISTP-A / ISTP-T)", MainCategory: "Explorer"},
                {Question: `I value the mastery of skills and hands-on experiences.`, 
                    SubCategory: "Virtuoso (ISTP-A / ISTP-T)", MainCategory: "Explorer"},
                    // Adventurer (ISFP-A / ISFP-T)
                {Question: `I am flexible and enjoy exploring new and creative experiences.`, 
                    SubCategory: "Adventurer (ISFP-A / ISFP-T)", MainCategory: "Explorer"},
                {Question: `I find joy in expressing myself through art and other forms of creativity.`, 
                    SubCategory: "Adventurer (ISFP-A / ISFP-T)", MainCategory: "Explorer"},
                {Question: `I appreciate the beauty and wonder in the world around me.`, 
                    SubCategory: "Adventurer (ISFP-A / ISFP-T)", MainCategory: "Explorer"},
                    // Entrepreneur (ESTP-A / ESTP-T)
                {Question: `I consider myself smart, energetic, and perceptive.`, 
                    SubCategory: "Entrepreneur (ESTP-A / ESTP-T)", MainCategory: "Explorer"},
                {Question: `I enjoy living on the edge and taking risks for potential rewards.`, 
                    SubCategory: "Entrepreneur (ESTP-A / ESTP-T)", MainCategory: "Explorer"},
                {Question: `I thrive in dynamic and fast-paced environments.`, 
                    SubCategory: "Entrepreneur (ESTP-A / ESTP-T)", MainCategory: "Explorer"},
                    // Entertainer (ESFP-A / ESFP-T)
                {Question: `I am spontaneous, energetic, and enthusiastic about life.`, 
                    SubCategory: "Entertainer (ESFP-A / ESFP-T)", MainCategory: "Explorer"},
                {Question: `I find joy in bringing excitement and entertainment to others.`, 
                    SubCategory: "Entertainer (ESFP-A / ESFP-T)", MainCategory: "Explorer"},
                {Question: `I prefer a lively and engaging lifestyle.`, 
                    SubCategory: "Entertainer (ESFP-A / ESFP-T)", MainCategory: "Explorer"},
            ]
        },

    },
    "SDPC Result": {
        'BS Information Technology': 'This program equips students with the knowledge and skills needed to design, develop, and manage information systems. It covers areas such as programming, database management, network security, and software development.',
        'BS Criminologyinology': 'Geared towards understanding the dynamics of crime and criminal behavior. Students learn about law enforcement, criminal justice systems, and crime prevention strategies.',
        'BS Psychologyology': 'Explores the scientific study of human behavior and mental processes. Topics include cognitive processes, social interactions, and psychological disorders.',
        'BS Nursing': 'Focuses on preparing students to provide high-quality healthcare. It includes training in patient care, medical procedures, and ethical considerations in nursing.',
        'BS Computer Engineering': 'Integrates computer science and electrical engineering principles. Students learn to design and develop computer hardware and software systems.',
        'BS Electronics Engineering': 'Concentrates on the study of electronic circuits and systems. It covers topics like digital electronics, communication systems, and signal processing.',
        'BS Industrial Engineering': 'Involves optimizing processes and systems within industries to enhance efficiency. Students learn about production planning, quality control, and supply chain management.',
        'BS Accountancy': 'Focuses on principles of financial accounting, auditing, and taxation. Graduates often pursue careers as accountants, auditors, or financial analysts.',
        'BS Tourism': 'Explores the management and promotion of tourism and travel. Students learn about hospitality, destination management, and tourism marketing.',
        'BS Hospitality': 'Concentrates on the management and operation of hospitality-related businesses such as hotels, restaurants, and resorts.',
        'BSBA Management Accounting': 'Integrates accounting principles with management strategies, preparing students for roles in financial management and decision-making.',
        'BSBA Financial Management': 'Emphasizes financial planning, analysis, and management within the context of business organizations.',
        'BSBA Marketing Management': 'Explores marketing strategies, consumer behavior, and market research to prepare students for roles in marketing and sales.',
        'Architect (INTJ-A / INTJ-T)': 'Imaginative and strategic thinkers, with a plan for everything.',
        'Logician (INTP-A / INTP-T)': 'Innovative inventors with an unquenchable thirst for knowledge.',
        'Commander (ENTJ-A / ENTJ-T)': 'Bold, imaginative and strong-willed leaders, always finding a way – or making one.',
        'Debater (ENTP-A / ENTP-T)': 'Smart and curious thinkers who cannot resist an intellectual challenge.',
        'Advocate (INFJ-A / INFJ-T)': 'Quiet and mystical, yet very inspiring and tireless idealists. Poetic, kind, and altruistic people, always eager to help a good cause.',
        'Protagonist (ENFJ-A / ENFJ-T)': 'Charismatic and inspiring leaders, able to mesmerize their listeners.',
        'Campaigner (ENFP-A / ENFP-T)': 'Enthusiastic, creative and sociable free spirits, who can always find a reason to smile.',
        'Logistician (ISTJ-A / ISTJ-T)': 'Practical and fact-minded individuals, whose reliability cannot be doubted.',
        'Defender (ISFJ-A / ISFJ-T)': 'Very dedicated and warm protectors, always ready to defend their loved ones.',
        'Executive (ESTJ-A / ESTJ-T)': 'Excellent administrators, unsurpassed at managing things – or people.',
        'Consul (ESFJ-A / ESFJ-T)': 'Extraordinarily caring, social and popular people, always eager to help.',
        'Virtuoso (ISTP-A / ISTP-T)': 'Bold and practical experimenters, masters of all kinds of tools.',
        'Adventurer (ISFP-A / ISFP-T)': 'Flexible and charming artists, always ready to explore and experience something new.',
        'Entrepreneur (ESTP-A / ESTP-T)': 'Smart, energetic and very perceptive people, who truly enjoy living on the edge.',
        'Entertainer (ESFP-A / ESFP-T)': 'Spontaneous, energetic and enthusiastic people – life is never boring around them.',
        'Depression': 'Feelings of sadness, hopelessness, and loss of interest in activities once enjoyed.',
        'Bipolar Disorder': 'Extreme mood swings between mania and depression.',
        'Cyclothymia': 'Less severe but longer-lasting mood swings than bipolar disorder.',
        'Generalized Anxiety Disorder (GAD)': 'Constant worry and anxiety about everyday situations.',
        'Panic Disorder': 'Sudden episodes of intense fear and physical symptoms like racing heart or shortness of breath.',
        'Social Anxiety Disorder': 'Fear of social situations and being judged by others.',
        'Phobias': 'Intense fear of specific objects or situations.',
        'Obsessive-Compulsive Disorder (OCD)': 'Unwanted thoughts (obsessions) and repetitive behaviors (compulsions) that are difficult to control.',
        'Post-Traumatic Stress Disorder (PTSD)': 'Symptoms like flashbacks, nightmares, and avoidance after experiencing a traumatic event.',
        'Acute Stress Disorder (ASD)': 'Similar to PTSD but occurring within a month of the traumatic event.',
        'Borderline Personality Disorder (BPD)': 'Unstable emotions, relationships, and self-image.',
        'Narcissistic Personality Disorder': 'Inflated sense of self-importance and lack of empathy.',
        'Antisocial Personality Disorder': 'Disregard for others\' rights and feelings.',
        'Schizophrenia': 'Distortions in thoughts, perceptions, and reality.',
        'Psychotic disorders': 'Other conditions causing hallucinations or delusions.',
        'Addiction': 'Dependence on substances or behaviors like gambling.',
        'Dementia': 'Decline in cognitive function due to various causes.'
    }
}