
export let Data = {

    YearLevel: [
        "Grade 11", "Grade 12", "Year 1", "Year 2", "Year 3", "Year 4", "Year 5",
    ],

    Gender: [
        "Male", "Female",
    ],

    Department: [
        "Medical", "Dental", "SDPC"
    ],
    
    Courses: [
        "STEM (SHS)", "ABM (SHS)", "GAS (SHS)", "TVL (SHS)", "HUMSS (SHS)", "Master in Business Admin", "AB Communication", "BS Information Technology", 
        "BS Criminology", "BS Psychology", "BS Nursing", "BS Computer Engineering", "BS Electronics Engineering", "BS Industrial Engineering", "BS Accountancy", 
        "BS Tourism Management", "BS Hospitality Management", "BSBA Management Accounting", "BSBA Financial Management", "BSBA Marketing Management", 
    ],

    Prescriptions: {
        SDPC: [
            "Individual Inventory",
            "Information Service",
            "Counseling Services",
            "Psychological Testing and Assessment Service",
            "Placement",
            "Referral",
            "Follow-up",
            "Research and Evaluation",
            "Auxiliary Services",
        ],
        Dental: [
            "Acetaminophen (Tylenol)",
            "Ibuprofen (Advil, Motrin)",
            "Naproxen (Aleve)",
            "Amoxicillin",
            "Clindamycin",
            "Penicillin VK",
            "Prednisone",
            "Dexamethasone",
            "Nystatin",
            "Chlorhexidine (for antibacterial use)",
            "Magic Mouthwash",
            "Lidocaine",
            "Not Listed above",
        ],
        Medical: [
            "Paracetamol (Acetaminophen)",
            "Ibuprofen",
            "Cetirizine",
            "Loperamide",
            "Diphenhydramine",
            "Oral Rehydration Solution",
            "Amoxicillin",
            "Cefuroxime",
            "Salbutamol Inhaler",
            "Hydrocortisone Cream",
            "Omeprazole",
            "Chlorphenamine",
            "Not Listed above",
        ],
    },
    Diagnosis: {
        SDPC: [
            "Course Selection Difficulties",
            "Decision-Making Difficulties",
            "Academic Performance Issues",
            "Procrastination Issues",
            "Academic Dishonesty",
            "Career Planning Difficulties",
            "Anxiety and Stress Management",
            "Depression",
            "Mood Swings Issues",
            "Adjustment Issues",
            "Homesickness",
            "Relationship Issues",
            "Self-Esteem Issues",
            "Bullying and Harassment",
            "Social Anxiety and Social Phobia",
            "Lack of Social Skills",
            "Substance Abuse and Addiction",
        ],
        Dental: [
            "Cavities",
            "Gingivitis",
            "Malocclusion",
            "Dental Erosion",
            "Oral Thrush",
            "Tooth Sensitivity",
            "Improper Brushing Technique",
            "Inadequate Flossing",
        ],
        Medical: [
            "Muscle pain",
            "Body aches",
            "Body Injury",
            "Headache",
            "Sore throat",
            "Cough",
            "Vomiting",
            "Diarrhea",
            "Fever",
            "Common Cold",
            "Bronchitis and Bronchiolitis",
            "Stomach Flu (Gastroenteritis)",
            "Hand, Foot and Mouth Disease (HFMD)",
            "Febrile Seizures",
            "Chickenpox",
            "Eczema",
            "Asthma",
            "Allergic Rhinitis (Allergies)",
            "Constipation",
            "Not listed above",

        ],
    },
    Services: {
        SDPC: [
            "Individual Inventory",
            "Information Service",
            "Counseling Services",
            "Psychological Testing and Assessment Service",
            "Placement",
            "Referral",
            "Follow-up",
            "Research and Evaluation",
            "Auxiliary Services",
        ],
        Dental: [
            "Conduct routine dental examination",
            "Dental consultation or treatment",
            "Referral",
            "Provision of initial dose of medicine",
            "Dental check-up",
            "Dental Certificates",
            "Dental Clearance",
            "Dental outreach programs",
        ],
        Medical: [
            "Medical consultation",
            "First aid services",
            "Medications service",
            "Nebulization services",
            "Blood pressure check-ups   ",
            "Annual physical examination",
            "Physical examinations",
            "Medical certificates",
            "Medical outreach programs",
        ],
    },
    Sickness: {
        SDPC: [
            "Persistent feelings of sadness or hopelessness",
            "Irritability, mood swings, or emotional highs and lows",
            "Social withdrawal and isolation",
            "Changes in sleep patterns (insomnia or excessive sleeping)",
            "Changes in appetite or weight","Restlessness or slowed movements",
            "Difficulty concentrating or making decisions",
            "Memory problems",
            "Racing thoughts or persistent worries",
            "Unexplained aches and pains",
            "Changes in energy levels (feeling fatigued or restless)",
            "Excessive fears or worries",
            "Intense feelings of guilt or worthlessness",
            "Difficulty regulating emotions",
            "Decline in academic or work performance",
            "Difficulty handling everyday tasks and responsibilities",
            "Difficulty falling asleep or staying asleep",
            "Experiencing nightmares or disturbing dreams",
            "Withdrawal from friends, family, and social activities",
            "Difficulty maintaining relationships",
            "Increased conflicts with others",
            "Increased use of alcohol, tobacco, or other substances as a way to cope",
            "Frequent headaches, stomachaches, or other unexplained physical complaints", 
            "Thoughts of death or suicide",
            "Expressing feelings of hopelessness or having no reason to live",
            "Not listed above",
        ],
        Dental: [
            "Breakdown of tooth",
            "Inflammation of the gums",
            "Advanced stage of gum disease",
            "Odor in the breath",
            "Pain or discomfort when consuming foods or drinks",
            "Gradual wearing away of tooth enamel, often due to acidic foods",
            "Abnormal cell growth in the oral cavity, including the lips, tongue, cheeks, and throat.",
            "Insufficient saliva production, leading to a dry and uncomfortable feeling in the mouth.",
            "Not listed above",
        ],
        Medical: [
            "High fever (over 103°F or 39.4°C)",
            "Chest pain",
            "Shortness of breath",
            "Severe abdominal pain",
            "Sudden severe headache",
            "Bleeding that doesn't stop",
            "Cough",
            "Wheezing",
            "Earache",
            "Vomiting",
            "Diarrhea",
            "Rashes,",
            "Developmental delays",
            "Difficulty breathing",
            "Fever",
            "Dizziness",
            "Difficulty swallowing",
            "Numbness",
            "Weakness",
            "Seizures",
            "Confusion",
            "Not listed above",
        ],
    },
}

